### ISSUE TITLE
What kind of items are available?

### ISSUE THREAD

**Issue by LySoon** [ExoticNx/properties#3]
can we get a wiki for furnitures :?

**Comment by ExoticNx** [comment]
its just any prop.

**Comment by ExoticNx** [comment]
Furniture = {
	{type = "Storage", items = {
		{name = "safe", maxAmount = 10, propName = "p_v_43_safe_s"}
	}},
}

make a new entry to this table.

**Comment by LySoon** [comment]
i mean some kind of new furnitures like Wardrobe, sink etc, music player?
if its fine i can try to add them by myself

**Comment by ExoticNx** [comment]
nothing, you would have to add all that yourself
