### ISSUE TITLE
Menu Stops Showing after restart

### ISSUE THREAD

**Issue by ImGrim** [ExoticNx/properties#6]
Was super amazed how this all worked, was working perfectly... But now the house doesn't even show on the map or the menu doesn't show at all, haven't changed anything but adding the safe into the house which worked perfectly... 

Would love for a fix because this is flipping amazing...

**Comment by ExoticNx** [comment]
Hmm never had that, any errors should cause any problems.

**Comment by ImGrim** [comment]
No errors man, script runs flawlessly other than the menu not showing up.. Nothing happens anymore, i cleared sever cache - it came back after 1 restart then it was gone again...

I don't currently have any other property scripts other than yours either, i'm so lost.

Edit: Is the key columns in the database supposed to be empty? key1 & key2 isn't showing anything, just blank fields - but it shows the player who purchased it

**Comment by ExoticNx** [comment]
yeah should be as i never implemented it.

Can you post a screen shot of each table in the database?

**Comment by ImGrim** [comment]
Ahh i see, Here's the screenshots from all the sm_* stuff in the database

![image](https://user-images.githubusercontent.com/62400511/82442036-d5258800-9a96-11ea-8bf1-529a0f066f76.png)

![image](https://user-images.githubusercontent.com/62400511/82442063-deaef000-9a96-11ea-8083-c340509c682d.png)

![image](https://user-images.githubusercontent.com/62400511/82442087-e79fc180-9a96-11ea-81d0-1509cffabe78.png)

![image](https://user-images.githubusercontent.com/62400511/82442111-f2f2ed00-9a96-11ea-8aa4-5602127f0b3b.png)

**Comment by ExoticNx** [comment]
could you show the data part.

**Comment by ImGrim** [comment]
![image](https://user-images.githubusercontent.com/62400511/82442507-b5db2a80-9a97-11ea-8923-8290ac276781.png)

![image](https://user-images.githubusercontent.com/62400511/82442515-ba074800-9a97-11ea-8ddf-242a83282a86.png)

![image](https://user-images.githubusercontent.com/62400511/82442531-c12e5600-9a97-11ea-8c79-575fced0083e.png)

![image](https://user-images.githubusercontent.com/62400511/82442539-c5f30a00-9a97-11ea-91e6-30667e2cf1bb.png)

**Comment by ExoticNx** [comment]
hmm odd
i cant seem to reproduce this.

**Comment by ImGrim** [comment]
It's really weird man, As i said. It has worked on initial install - then when i cleared my cache it came back, but both times after a server restart it doesn't allow me to even interact with the menu... the script is showing running in resmon, so i'm not too sure.

I might drop all tables and just try again, it's the last thing i can think off personally w/ a reinstall of the scripts, i'll post a update here if anything changes

**Comment by ExoticNx** [comment]
sounds good, yeah i wasnt able to do it so idk.

**Comment by ExoticNx** [comment]
wish i could help more :(

**Comment by ImGrim** [comment]
Hey man, Update: Got it working, i don't know how or why. but for now it seems like it's now functioning as intended - restart and menu shows and everything saves :) Thank you for the great script, sorry for wasting your time!

**Comment by ExoticNx** [comment]
glad you got it fixed :)

**Comment by Matetv** [comment]
Have the same problem! After restarting the server, the menu no longer works! You can click on it briefly, but then it belongs right back! How did you develop it

**Comment by Matetv** [comment]
https://www.youtube.com/watch?v=Py67gyKWm7Y
